"""
Problem 094 of Project Euler.

https://projecteuler.net/problem=094

Let (a, a, a +- 1) be the triangle.
Split it in to so that thee two resulting triangles have edges (a, (a +- 1)/2, h).
Since the area of the trianlge must be integer-valued, so too must (a +- 1)/2 and h.
Therefore, ((a +- 1)/2, h, a) is a pythagorean triple,
and can be generated by Euclid's formula.

If (a +- 1)/2 is generated by k(u^2 - v^2), then

    -+1 = a - (a +- 1) = k(u^2 + v^2) - 2k(u^2 - v^2) = k(3v^2 - u^2).

This implies that k=1, so

    u = sqrt(3v^2 +- 1).

If (a +- 1)/2 is generated by 2kuv, then

    -+1 = a - (a +- 1) = k(u^2 + v^2) - 2kuv = k(u^2 + v^2 - 2uv).

Again, this means k=1.  Solving for u yields

    u = (4v + sqrt(16v^2 - 4v^2 -+ 4))/2 = 2v + sqrt(3v^2 -+ 1).

In either case, we require 3v^2 +- 1 be a perfect square x^2.
Since the quadratic residues mod 3 are {0, 1} adn 3v^2 - 1 (mod 3) = 2,
we only need to check for v such that 3v^2 + 1 = x^2.
Therefore, it suffices to solve Pell's equation

    x^2 - 3v^2 = 1,

where x = sqrt(3v^2 + 1)
By inspection, (2, 1) is a solution, and all other solution can be obtained by

    x_{k + 1} = 2x_k + 3y_k,    y_{k + 1} = 2y_k + x_k.

Back to the case where u = sqrt(3v^2 + 1),
we then have a = u^2 + v^2 and perimeter = 3a + 1 = 4v^2 + 4
In the second case where u = 2v + sqrt(3v^2 + 1),
we have a = u^2 + v^2 and perimeter = 3a - 1 = 24v^2 + 12vx + 2.
"""


def problem094(limit=1_000_000_000):
    summation = 0
    x = 2
    v = 1
    while True:
        vv = v * v
        p1 = 12 * vv + 4
        p2 = 24 * vv + 12 * v * x + 2
        if p1 >= limit:
            return summation
        summation += p1
        if p2 < limit:
            summation += p2
        x, v = 2 * x + 3 * v, x + 2 * v
